name: Conviso Security Test Suite
on:
  push:
    branches: [staging]

jobs:
  conviso-test-suite:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli:unstable
      env:
        CONVISO_API_KEY: ${{secrets.CONVISO_API_KEY}}
        CONVISO_COMPANY_ID: '11'
    steps:
      - uses: actions/checkout@v4
      - name: Run AST
        run: conviso ast run
