const fs = require("fs");
const path = require("path");

const graphqlDocsDir = path.join(
  __dirname,
  "docs",
  "api",
  "graphql",
  "documentation"
);
const hasGraphqlDocs =
  fs.existsSync(graphqlDocsDir) &&
  fs.readdirSync(graphqlDocsDir, { withFileTypes: true }).length > 0;

const apiItems = [
  "api/api-overview",
  "api/graphql/playground",
];

if (hasGraphqlDocs) {
  apiItems.push({
    type: "category",
    label: "References",
    items: [{ type: "autogenerated", dirName: "api/graphql/documentation" }],
  });
}

module.exports = {
  docs: [
    'index',
    {
      type: "category",
      label: "Core Workflows",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Posture Management",
          collapsed: true,
          items: [
            'posture-management/posture',
            'posture-management/vulnerability-kpi',
            'posture-management/security-champions-metrics',
            'posture-management/aspm-coverage',
          ],
        },
        {
          type: "category",
          label: "Vulnerability Management",
          collapsed: true,
          items: [
            'vulnerability-management/workflow-status',
            'vulnerability-management/process',
          ],
        },
        {
          type: "category",
          label: "Project Management",
          collapsed: true,
          items: [
            'project-management/workflow-status',
            'project-management/process',
          ],
        },
        {
          type: "category",
          label: "Threat Modeling",
          collapsed: true,
          items: [
            'threat-modeling/management-threat-modeling-artifacts',
            'threat-modeling/create-threat-modeling',
            'threat-modeling/threat-modeling-artefact',
            'threat-modeling/create-a-new-threat-modeling-artifact',
            'threat-modeling/management-projects-with-requirements-based-in-tm',
          ],
        },
        {
          type: "category",
          label: "Scanning your Application",
          collapsed: true,
          items: [
            {
              type: 'doc',
              label: 'Scan Application with Conviso',
              id: 'security-scans/conviso-ast/conviso-ast'
            },
            {
              type: 'doc',
              label: 'Scan Application with Conviso DAST',
              id: 'security-scans/conviso-dast/conviso-dast'
            },
            {
              type: 'doc',
              label: 'Software Bill of Materials (SBOM)',
              id: 'security-scans/conviso-sbom/conviso-sbom'
            },
            {
              type: 'doc',
              label: 'Scan Container with Conviso',
              id: 'security-scans/conviso-containers/conviso-containers'
            },
            {
              type: 'doc',
              label: 'Pull Request Scanning',
              id: 'security-scans/pull-requests/pull-requests'
            },
            'security-scans/security-gate',
          ]
        },
      ],
    },
    {
      type: "category",
      label: "Platform Features",
      items: [
        {
          type: "category",
          label: "AI Capabilities",
          link: {
            type: "doc",
            id: "platform/appsec-ai-agent",
          },
          collapsed: true,
          items: [
            'ai-capabilities/false-positive-analysis',
            'ai-capabilities/how-to-fix',
            'ai-capabilities/autofix',
            'integrations/conviso-mcp-server',
            'integrations/conviso-skills',
          ],
        },
        {
          type: "category",
          label: "Platform User Guide",
          items: [
            'platform/security-feed',
            'platform/dashboard',
            'platform/vulnerabilities',
            'platform/projects',
            'platform/requirements',
            'platform/security-gate',
            'platform/asset-management',
            'platform/sbom-management',
            'platform/notifications-center',
            'platform/policies',
            'platform/threat-modeling',
            'platform/user-management',
            'platform/credentials',
            'platform/dark-mode',
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guides and Operations",
      items: [
        {
          type: "category",
          label: "Role-Based Guides",
          items: [
            'general/role-based-guide-devsecops',
            'general/role-based-guide-developer',
            'general/role-based-guide-penetration-tester',
            'general/role-based-guide-appsec-engineer',
            'general/role-based-guide-appsec-manager',
            'general/role-based-guide-pci-manager',
            'general/role-based-guide-security-manager'
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Integration and Automations",
      items: [
        'new-cli',
        {
          type: "category",
          label: "Integrations",
          items: [
            'integrations/integrations_intro',
            {
              type: "category",
              label: "Authentication/SSO",
              items: [
                'integrations/google',
                'integrations/microsoft-entra-id',
                'integrations/saml'
              ]
            },
            {
              type: "category",
              label: "CI/CD",
              items: [
                'integrations/azure-pipelines-cli',
                'integrations/azure-pipelines-graph',
                'integrations/bitbucket-pipelines',
                'integrations/circleci',
                'integrations/codefresh',
                'integrations/github-actions',
                'integrations/gitlab',
                'integrations/jenkins',
                'integrations/jenkins-single-pipeline'
              ]
            },
            {
              type: "category",
              label: "Data Analytics",
              items: [
                'integrations/datastudio',
                'integrations/powerbi'
              ]
            },
            {
              type: "category",
              label: "Developer Portal",
              items: [
                'integrations/backstage',
              ]
            },
            {
              type: "category",
              label: "Defect/Bug Tracking",
              items: [
                'integrations/azure-boards',
                'integrations/businessmap',
                'integrations/clickup',
                'integrations/jira',
                'integrations/servicenow'
              ]
            },
            {
              type: "category",
              label: "Notifications",
              items: [
                'integrations/microsoft-teams',
                'integrations/slack'
              ]
            },
            {
              type: "category",
              label: "Pentest Tools",
              items: [
                'integrations/burp',
              ]
            },
            {
              type: "category",
              label: "Scanners",
              items: [
                'integrations/checkmarx',
                'integrations/dependency-track',
                'integrations/fortify',
                'integrations/github-advanced-security',
                'integrations/sonarcloud',
                'integrations/sonarqube',
                'integrations/mobsf',
              ]
            },
            {
              type: "category",
              label: "Application Lifecycle Management",
              link: {
                type: 'generated-index',
                title: 'Application Lifecycle Management',
              },
              items: [
                {
                  type: "category",
                  label: "Azure DevOps",
                  link: {
                    type: 'doc',
                    id: 'integrations/azure-devops',
                  },
                  items: [
                    'integrations/azure-devops-ast-orchestrator',
                  ]
                },
                {
                  type: "category",
                  label: "GitHub",
                  link: {
                    type: 'doc',
                    id: 'integrations/github',
                  },
                  items: [
                    'integrations/github-ast-orchestrator',
                  ]
                },
              ]
            },        
          ]
        },
        {
          type: "category",
          label: "API Reference",
          items: apiItems,
        },
      ],
    },
  ],
  releaseSidebar: [
    {
      type: "category",
      label: "Release Notes",
      collapsible: false,
      collapsed: false,
      items: [
        'releases/intro',
        {
          type: "category",
          label: "Release Notes 🚀",
          items: [
            'releases/release4.25',
            'releases/release4.24',
            'releases/release4.23',
            'releases/release4.22',
            'releases/release4.21',
            'releases/release4.20',
            'releases/release4.19',
            'releases/release4.18',
            'releases/release4.17',
            'releases/release4.16',
            'releases/release4.15',
            'releases/release4.14',
            'releases/release4.13',
            'releases/release4.12',
            'releases/release4.11',
            'releases/release4.10',
            'releases/release4.9',
            'releases/release4.8',
            'releases/release4.7',
            'releases/release4.6',
            'releases/release4.5',
            'releases/release4.4',
            'releases/release4.3',
            'releases/release4.2',
            'releases/release4.1',
            'releases/release4.0',
            'releases/release3.9',
            'releases/release3.8',
            'releases/release3.7',
            'releases/release3.6',
            'releases/release35',
            'releases/release34',
            'releases/release33',
            'releases/release32',
            'releases/release31',
            'releases/appsecflow305',
            'releases/appsecflow304',
            'releases/appsecflow302'
          ] // <-- Esse array fecha aqui, sem colchete extra depois
        }
      ]
    }
  ],
}
