const fs = require("fs");
const path = require("path");

const graphqlDocsDir = path.join(
  __dirname,
  "docs",
  "api",
  "graphql",
  "documentation"
);
const hasGraphqlDocs =
  fs.existsSync(graphqlDocsDir) &&
  fs.readdirSync(graphqlDocsDir, { withFileTypes: true }).length > 0;

const apiItems = [
  "api/api-overview",
  "api/graphql/playground",
];

if (hasGraphqlDocs) {
  apiItems.push({
    type: "category",
    label: "References",
    items: [{ type: "autogenerated", dirName: "api/graphql/documentation" }],
  });
}

module.exports = {
  docs: [
    'index',
    {
      type: "category",
      label: "Platform User Guide",
      items: [
        'platform/appsec-ai-agent',
        'platform/asset-management',
        'platform/credentials',
        'platform/dashboard',
        'platform/notifications',
        'platform/policies',
        'platform/projects',
        'platform/requirements',
        'platform/risk-context-funnel',
        'platform/risk-score',
        'platform/sbom-management',
        'platform/security-feed',
        'platform/threat-modeling',
        'platform/user-management',
        'platform/vulnerabilities'
      ],
    },
    {
      type: "category",
      label: "Scanning your Application",
      items: [
        'cli/installation',
        'cli/ast',
        {
          type: 'doc',
          label: 'Scan Application with Conviso',
          id: 'security-scans/conviso-ast/conviso-ast'
        },
        {
          type: 'doc',
          label: 'Scan Application with Conviso DAST',
          id: 'security-scans/conviso-dast/conviso-dast'
        },
        {
          type: 'doc',
          label: 'Software Bill of Materials (SBOM)',
          id: 'security-scans/conviso-sbom/conviso-sbom'
        },
        {
          type: 'doc',
          label: 'Scan Container with Conviso',
          id: 'security-scans/conviso-containers/conviso-containers'
        },
        'cli/security-gate',
      ]
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        'integrations/integrations_intro',
        {
          type: "category",
          label: "Authentication/SSO",
          items: [
            'integrations/google',
            'integrations/microsoft-entra-id',
            'integrations/saml'
          ]
        },
        {
          type: "category",
          label: "CI/CD",
          items: [
            'integrations/aws-codebuild',
            'integrations/azure-pipelines-cli',
            'integrations/azure-pipelines-graph',
            'integrations/bitbucket-pipelines',
            'integrations/circleci',
            'integrations/codefresh',
            'integrations/github-actions',
            'integrations/gitlab',
            'integrations/jenkins',
            'integrations/jenkins-single-pipeline'
          ]
        },
        {
          type: "category",
          label: "Data Analytics",
          items: [
            'integrations/datastudio',
            'integrations/powerbi'
          ]
        },
        {
          type: "category",
          label: "Defect/Bug Tracking",
          items: [
            'integrations/azure-boards',
            'integrations/businessmap',
            'integrations/clickup',
            'integrations/jira',
            'integrations/servicenow'
          ]
        },
        {
          type: "category",
          label: "Notifications",
          items: [
            'integrations/microsoft-teams',
            'integrations/slack'
          ]
        },
        {
          type: "category",
          label: "Scanners",
          items: [
            'integrations/checkmarx',
            'integrations/dependency-track',
            'integrations/fortify',
            'integrations/github-advanced-security',
            'integrations/sonarcloud',
            'integrations/sonarqube',
            'integrations/mobsf',
          ]
        },
        {
          type: "category",
          label: "Source Control",
          items: [
            {
              type: "category",
              label: "GitHub",
              link: {
                type: 'doc',
                id: 'integrations/github',
              },
              items: [
                'integrations/github-ast-orchestrator',
              ]
            },
          ]
        },
      ]
    },
    {
      type: "category",
      label: "API",
      items: apiItems,
    },
    'new-cli',
  ],
  releaseSidebar: [
    {
      type: "category",
      label: "Release Notes",
      collapsible: false,
      collapsed: false,
      items: [
        'releases/intro',
        {
          type: "category",
          label: "Release Notes 🚀",
          items: [
            'releases/release4.19',
            'releases/release4.18',
            'releases/release4.17',
            'releases/release4.16',
            'releases/release4.15',
            'releases/release4.14',
            'releases/release4.13',
            'releases/release4.12',
            'releases/release4.11',
            'releases/release4.10',
            'releases/release4.9',
            'releases/release4.8',
            'releases/release4.7',
            'releases/release4.6',
            'releases/release4.5',
            'releases/release4.4',
            'releases/release4.3',
            'releases/release4.2',
            'releases/release4.1',
            'releases/release4.0',
            'releases/release3.9',
            'releases/release3.8',
            'releases/release3.7',
            'releases/release3.6',
            'releases/release35',
            'releases/release34',
            'releases/release33',
            'releases/release32',
            'releases/release31',
            'releases/appsecflow305',
            'releases/appsecflow304',
            'releases/appsecflow302'
          ] // <-- Esse array fecha aqui, sem colchete extra depois
        }
      ]
    }
  ],
}
