name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.PROJECT_KEY}}
   steps:
   - uses: actions/checkout@v3

   - name: AST
     run: conviso ast run
   
   - name: Security Gate
     run: conviso vulnerability assert-security-rules --rules-file 'security-gate-policy.yml'
